ingress-nginx:
  controller:
    watchIngressWithoutClass: true
    allowSnippetAnnotations: true

    ingressClassResource:
      name: nginx  # default: nginx
      enabled: true
      default: true
      controllerValue: k8s.io/ingress-nginx
