#defaults file for gitops
os_arch: '{{ ansible_architecture }}'
system_arch: '{{ ''amd64'' if ansible_architecture == ''x86_64'' else ''arm64'' }}'
os_platform: linux
# @vars for Helm
helm_binary_path: /usr/bin/helm
helm_path: /usr/bin
helm_url: https://get.helm.sh/helm-v{{ helm_version }}-{{ os_platform }}-{{ system_arch }}.tar.gz
#See https://github.com/helm/helm/releases
helm_version: 3.14.3
# @vars for Kustomize
k7e_binary_path: /usr/bin
k7e_version: 5.4.1
k7e_core_download: https://github.com/kubernetes-sigs/kustomize/releases/download/kustomize%2Fv{{ k7e_version }}/kustomize_v{{ k7e_version }}_linux_{{ system_arch }}.tar.gz
## @ars for Kustomize Plugins 
ksops_download_url: https://github.com/viaduct-ai/kustomize-sops/releases/download/v{{ k7e_plugins.ksops.version }}/ksops_{{ k7e_plugins.ksops.version }}_{{ os_platform }}_{{ os_arch }}.tar.gz
khelm_download_url: https://github.com/mgoltzsche/khelm/releases/download/v{{ k7e_plugins.khelm.version }}/khelm-linux-{{ system_arch }}
k7e_plugins:
    ksops:
        enabled: true
        version: 4.3.1
    khelm:
        enabled: true
        version: 2.3.3
# @vars for argocd
argocd_namespace: argocd
argocd_version: 2.10.6
argocd_manifests: https://raw.githubusercontent.com/argoproj/argo-cd/v{{ argocd_version }}/manifests/install.yaml
argocd_binary_path: /usr/bin
argocd_cli_url: https://github.com/argoproj/argo-cd/releases/download/v{{ argocd_version }}/argocd-{{ os_platform }}-{{ system_arch }}
argocd_new_password: argocdadmin0#
# @vars for argocd gitlab repository
kube_server: https://kubernetes.default.svc
git_repo:
    gitlab_url: ENC[AES256_GCM,data:XtjlKiY5yUqb1SMJhbl1M2Rhl3Vu4BchSysdWs4aVEcfFEFtHuVIx8EpbnJZDiZEPX1YxtY/yg==,iv:XsglrVSc7VfXlgs/nvKeAorFFiBS367FmkVdAQQb2tc=,tag:qT63MOZlZNACzEhU78ZVBg==,type:str]
    gitlab_password: ENC[AES256_GCM,data:+gz50gTlVCEH/Ntvrp2H,iv:m0nW1vfMSSD6m75cl7etXHwVpzq4FKwXHFfoMIxVjB8=,tag:nuyNIZgSv1c/f+lkKGT/1Q==,type:str]
    gitlab_username: ENC[AES256_GCM,data:EOOvBsLc7w==,iv:Ofl/SrALlLvED54IrgSGJxDuZ/PILI5eWsLtFPADrP0=,tag:OBlzL41DwWgFLUz2bhxZGA==,type:str]
    repoistory_type: ENC[AES256_GCM,data:YbmX,iv:TYeoyRJZMJFOv468A1FlC1UiCx2cOZQqDWQzrVmCtEU=,tag:1zEmXyCUiJENHO/ITOHFYQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1yya5xs2rlqsualafaca3a03caceahmxucudm5uld7dr0g2utyqrq6ph3gl
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhY0Q2UXFOaEYyb05NUzZs
            L2NWRytvckJhSElCN3hLMnIwQkgrWmdNZzFvClpubnA5dXFoMFRFSVdzMjBZelkw
            Mk9NZ3EwSDhRZkZYdjd6M3lSd3ZsMGsKLS0tIDQ3WXVKaDBEL1VIK0FjelhjVmdJ
            NEg1aGJaWVRHRFBHd0tqaFRRMzBuaDgKzAjpsDJ5duu1tJD3oAkUuVRcYCoq5T1x
            hl5OimMBu1l0QgazfCMwXsRpE1Mt/qNESxTRFPxMzNjTFX0gYvGp0A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-06-11T17:30:33Z"
    mac: ENC[AES256_GCM,data:i1cESz6MNZdBnvsYrmcIxoIke1pYvQ9CGsdSTQ0uhH+8JT0dyDjYwYxHuH2lRdCIXvaV4q/+ARJb0xGg1mLZ86C1PifCdbbfYucvOkHeg0kuu0gVBl+F30e6ht3uU3WsgG877OSghngRn4gf6P8UdD1O7KKGsZrmJlV+0ZPKNXM=,iv:wIVQNwJ5NmWAKmE/3TA0VA91NMaP4vfT+Hhm1YyKYPs=,tag:XSP95XeBlzWkoQ0U9yU34w==,type:str]
    pgp: []
    encrypted_regex: ^git_repo$
    version: 3.8.1
