version: '3'

includes:
  env: ./.taskfiles/env.yml
  nodes: ./.taskfiles/nodes.yml
  cluster: ./.taskfiles/cluster.yml
  policy: ./.taskfiles/kyverno.yml

tasks:
  help:
    silent: true
    cmds: 
      - sh hack/help.sh