---
# @vars for haproxy and keepalived
vip_address: 10.254.100.99

<<<<<<< HEAD
haproxy_metrics_isenabled: true
lua_version: 5.3.6

keepalived_metrics_isenabled: true
=======
kame_isEnabled: true
>>>>>>> 7af34abd874d3d234cbd9d26cc9fbbb9bcf899a8
kame_version: 1.3.3
sys_arch: '{{ ''amd64'' if ansible_architecture == ''x86_64'' else ''arm64'' }}'
kame_archive_path:  "/tmp/keepalived_exporter-{{ kame_version }}.linux-{{ sys_arch }}"
kame_url: "https://github.com/mehdy/keepalived-exporter/releases/download/v{{ kame_version }}/keepalived-exporter-{{ kame_version }}.linux-{{ sys_arch }}.tar.gz"


# @vars for firewalld config
controlplane_firewall_ports:
  - 10248
  - 10249
  - 9099
  - 2379
  - 2380
  - 10250
  - 6443
  - 10256
  - 10257
  - 10259

workernode_firewall_ports:
  - 10259
  - 10250
  - '30000-32767' 

firewall_services:
  - http
  - https