{
 "title": "Keepalived Exporter",
 "time": { "from": "now-12h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "instance",
    "query": {
     "query": "label_values(keepalived_up, instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Keepalived Status",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "keepalived_up{instance=\"$instance\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "VRRP State",
   "type": "stat",
   "gridPos": { "h": 5, "w": 9, "x": 3, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "keepalived_vrrp_state{instance=\"$instance\"}",
     "legendFormat": "{{ iname }} / {{ ip_address }}"
    }
   ]
  },
  {
   "title": "Advertisements",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(keepalived_advertisements_sent_total{instance=\"$instance\"}[$__rate_interval])",
     "legendFormat": "{{ iname }} - sent"
    },
    {
     "expr": "rate(keepalived_advertisements_received_total{instance=\"$instance\"}[$__rate_interval])",
     "legendFormat": "{{ iname }} - received"
    }
   ]
  },
  {
   "title": "Script Status",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "keepalived_script_status{instance=\"$instance\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Script State",
   "type": "stat",
   "gridPos": { "h": 5, "w": 9, "x": 3, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "keepalived_script_state{instance=\"$instance\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Gratuitous ARP Delay",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "rate(keepalived_gratuitous_arp_delay_total{instance=\"$instance\"}[$__rate_interval])",
     "legendFormat": "{{ iname }}"
    }
   ]
  },
  {
   "title": "Master Changes",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(keepalived_become_master_total{instance=\"$instance\"}[$__rate_interval])",
     "legendFormat": "{{ iname }} - become"
    },
    {
     "expr": "rate(keepalived_release_master_total{instance=\"$instance\"}[$__rate_interval])",
     "legendFormat": "{{ iname }} - release"
    }
   ]
  },
  {
   "title": "Priority Zero",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(keepalived_priority_zero_sent_total{instance=\"$instance\"}[$__rate_interval])",
     "legendFormat": "{{ iname }} - sent"
    },
    {
     "expr": "rate(keepalived_priority_zero_received_total{instance=\"$instance\"}[$__rate_interval])",
     "legendFormat": "{{ iname }} - received"
    }
   ]
  },
  {
   "title": "Errors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(keepalived_advertisements_interval_errors_total{instance=\"$instance\"}[$__rate_interval])",
     "legendFormat": "{{ iname }} - Advertisement interval errors"
    },
    {
     "expr": "rate(keepalived_packet_length_errors_total{instance=\"$instance\"}[$__rate_interval])",
     "legendFormat": "{{ iname }} - Packet length errors"
    },
    {
     "expr": "rate(keepalived_ip_ttl_errors_total{instance=\"$instance\"}[$__rate_interval])",
     "legendFormat": "{{ iname }} - IP TTL errors"
    },
    {
     "expr": "rate(keepalived_invalid_type_received_total{instance=\"$instance\"}[$__rate_interval])",
     "legendFormat": "{{ iname }} - Invalid type received"
    },
    {
     "expr": "rate(keepalived_address_list_errors_total{instance=\"$instance\"}[$__rate_interval])",
     "legendFormat": "{{ iname }} - Address list errors"
    },
    {
     "expr": "rate(keepalived_authentication_invalid_total{instance=\"$instance\"}[$__rate_interval])",
     "legendFormat": "{{ iname }} - Authentication invalid"
    },
    {
     "expr": "rate(keepalived_authentication_failure_total{instance=\"$instance\"}[$__rate_interval])",
     "legendFormat": "{{ iname }} - Authentication failure"
    },
    {
     "expr": "rate(keepalived_authentication_mismatch_total{instance=\"$instance\"}[$__rate_interval])",
     "legendFormat": "{{ iname }} - Authentication mismatch"
    }
   ]
  }
 ]
}