apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
configMapGenerator:
  - name: misc-dashboards
    files:
      - argocd.json 
      - keepalived.json
      - haproxy.json
    options:
      labels:
        grafana_dashboard: "1"
      annotations:
        grafana_folder: Custom
        argocd.argoproj.io/sync-options: Replace=true