apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: monitoring

resources:
  - grafana
  - argocd
  - scrapeconfig

patches:
  - path: patches/prometheuses.yaml
  - path: patches/prometheusagents.yaml
  - path: patches/alertmanagers.yaml

helmCharts:
  - name: kube-prometheus-stack
    includeCRDs: true
    releaseName: kube-prometheus-stack
    version: "58.5.0"
    repo: https://prometheus-community.github.io/helm-charts
    valuesFile: values.yaml