apiVersion: monitoring.coreos.com/v1alpha1
kind: ScrapeConfig
metadata:
  name: haproxy
  namespace: monitoring
spec:
  staticConfigs:
    - targets:
        - 10.254.100.112:8404
        - 10.254.100.123:8404
      labels:
        vip: lb
  metricsPath: /metrics
  relabelings:
    - targetLabel: job
      replacement: haproxy
      action: replace