---
- name: Configure HAProxy Load Balancer
  hosts: halb, kube_controlplanes
  become: true
  tags: haproxy
  tasks:
    - name: HAProxy configuration
      block:
        - name: Install and configure HAProxy 
          include_tasks: tasks/01-haproxy.yml

        - name: Ensure HAProxy is restared
          systemd:
            name: haproxy
            state: restarted
      when: inventory_hostname == 'halb'

#####################################################

- name: Initialize Kubernetes Cluster
  hosts: kube_controlplanes
  tags: cluster
  become: true
  collections:
    - ansible.builtin
    - ansible.posix
    - community.general
    - kubernetes.core
  vars:
    haproxy_ip: 10.254.100.92
  vars_files:
    - vars/main.yml
  roles:
    #- role: ../roles/pre-setup
      #- role: ../roles/containerd
      #- role: ../roles/kubeadm
    - role: ../roles/gitops

#####################################################

- name: Configure firewalld on all hosts
  hosts: kube_cluster, etcd
  tags: firewall
  become: true
  tasks:
    - name: Enable firewalld and permit necessary ports and services
      include_tasks: tasks/00-allow_firewall.yml 

  handlers:
    - name: Reload firewalld
      service:
        name: firewalld
        state: restarted
...
