---
- name: Configure HAProxy Load Balancer with Keepalived
  hosts: haproxylb, kube_controlplanes
  become: true
  tags: haproxy
  vars_files:
    - vars/main.yml
  # vars:
  #   vip_address: 10.254.100.99
  tasks:
    - name: Install and configure HAProxy and Keepalived
      include_tasks: tasks/01-haproxy.yml
      when: inventory_hostname in groups['haproxylb']


- name: Initialize Kubernetes Cluster
  hosts: kube_cluster
  tags: cluster
  become: true
  collections:
    - ansible.builtin
    - ansible.posix
    - community.general
    - kubernetes.core
  vars_files:
    - vars/main.yml
  roles:
    - role: ../roles/pre-setup
    - role: ../roles/containerd
    - role: ../roles/kubeadm
    - role: ../roles/gitops
...