---
- name: Check if Helm binary already exists
  stat:
    path: "{{ helm_binary_path }}"
  register: check_helm

- name: Get Helm version
  shell: |
    "{{ helm_binary_path }} version"
  changed_when: false
  failed_when: false
  register: existing_helm_version

- name: Ensure Helm is downloaded and extracted
  block:
    - name: Download and extract Helm
      unarchive:
        remote_src: true
        src: "{{ helm_url }}"
        dest: /tmp/
        owner: root
        group: root
        mode: 0755
    - name: Copy Helm binary to destination
      copy:
        remote_src: true
        src: "/tmp/{{ os_platform }}-{{ system_arch }}/helm"
        dest: "{{ helm_path}}"
  when: >
    not check_helm.stat.exists
    or helm_version not in existing_helm_version.stdout