cert-manager:
  installCRDs: true

  ingressShim:
    defaultIssuerName: letsencrypt-stagging
    defaultIssuerKind: ClusterIssuer

  # prometheus:
  #   enabled: true
  #   servicemonitor:
  #     enabled: true