loki:
  deploymentMode: SingleBinary

  chunksCache:
    enabled: true
    allocatedMemory: 256
  resultsCache:
    enabled: true
    allocatedMemory: 256

  lokiCanary:
    enabled: false

  gateway:
    service:
      labels:
        prometheus.io/service-monitor: "false"

  ingress:
    enabled: true
    ingressClassName: nginx
    annotations:
      kubernetes.io/tls-acme: "true"
      cert-manager.io/cluster-issuer: letsencrypt
    hosts:
      - loki.k8s.coralio.co
    tls:
      - secretName: loki-tls
        hosts:
          - loki.k8s.coralio.co

  loki:
    memberlist:
      join_members: ["loki-memberlist"]

    limits_config:
      retention_period: 30d
    compactor:
      compaction_interval: 10m
      retention_enabled: true
      retention_delete_delay: 2h
      retention_delete_worker_count: 150
      delete_request_store: s3

    schemaConfig:
      configs:
        - from: "2022-01-11"
          store: tsdb
          object_store: s3
          schema: v13
          index:
            prefix: loki_index_
            period: 24h
          chunks:
            period: 24h

  read:
    replicas: 0
  write:
    replicas: 0
  backend:
    replicas: 0


    extraArgs:
      - -config.expand-env=true


  test:
    enabled: false

  monitoring:
    dashboards:
      enabled: true
      annotations:
        grafana_folder: Loki
    rules:
      enabled: true
    selfMonitoring:
      enabled: false
    serviceMonitor:
      enabled: true
      metricRelabelings:
        - action: drop
          sourceLabels: ["__name__"]
          regex: loki_(request_duration|logql_querystats_bytes_processed_per)_seconds_bucket