apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ingress-nginx
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io 
spec:
  destination:
    namespace: ingress-nginx
    server: https://kubernetes.default.svc
  project: apps
  source:
    repoURL: https://gitlab.com/chxmxii/cluster-template-coralio.git
    path: kubernetes/apps/networking/nginx-ingress-controller/chart
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true

