apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: vault
spec:
  provider:
    vault:
      auth:
        tokenSecretRef:
          key: {{.Values.vaultStore.tokenSecretRef.key }}
          name: {{.Values.vaultStore.tokenSecretRef.name }}
      path: {{.Values.vaultStore.path }}
      server: {{.Values.vaultStore.server }}
      version: {{.Values.vaultStore.version }}